pico-8 cartridge // http://www.pico-8.com
version 42
__lua__
-- probe: the FULL UTF-8 -> P8SCII glyph decode table for text-format
-- carts, one case per codepoint: chars 16-31 (shape/punctuation glyphs),
-- 128-153 (symbols/emoji), 154-253 (kana), 254-255, plus the U+FE0F
-- emoji-variation-selector forms. Each case reads back #s and ord(s) for
-- a string literal holding that codepoint's raw UTF-8. Notable captured
-- quirks: the five button/arrow glyphs (131/139/142/145/148) decode ONLY
-- with a trailing U+FE0F (bare, they stay as raw UTF-8 bytes -- see the
-- g131/g139/g142/g145/g148 lines expecting len=3/4), while every other
-- entry decodes bare and leaves a trailing U+FE0F behind as raw bytes
-- (v151 expects len=4).
do local s="▮" printh("RESULT g16 u25ae len="..#s.." b="..ord(s)) end
do local s="■" printh("RESULT g17 u25a0 len="..#s.." b="..ord(s)) end
do local s="□" printh("RESULT g18 u25a1 len="..#s.." b="..ord(s)) end
do local s="⁙" printh("RESULT g19 u2059 len="..#s.." b="..ord(s)) end
do local s="⁘" printh("RESULT g20 u2058 len="..#s.." b="..ord(s)) end
do local s="‖" printh("RESULT g21 u2016 len="..#s.." b="..ord(s)) end
do local s="◀" printh("RESULT g22 u25c0 len="..#s.." b="..ord(s)) end
do local s="▶" printh("RESULT g23 u25b6 len="..#s.." b="..ord(s)) end
do local s="「" printh("RESULT g24 u300c len="..#s.." b="..ord(s)) end
do local s="」" printh("RESULT g25 u300d len="..#s.." b="..ord(s)) end
do local s="¥" printh("RESULT g26 ua5 len="..#s.." b="..ord(s)) end
do local s="•" printh("RESULT g27 u2022 len="..#s.." b="..ord(s)) end
do local s="、" printh("RESULT g28 u3001 len="..#s.." b="..ord(s)) end
do local s="。" printh("RESULT g29 u3002 len="..#s.." b="..ord(s)) end
do local s="゛" printh("RESULT g30 u309b len="..#s.." b="..ord(s)) end
do local s="゜" printh("RESULT g31 u309c len="..#s.." b="..ord(s)) end
do local s="█" printh("RESULT g128 u2588 len="..#s.." b="..ord(s)) end
do local s="▒" printh("RESULT g129 u2592 len="..#s.." b="..ord(s)) end
do local s="🐱" printh("RESULT g130 u1f431 len="..#s.." b="..ord(s)) end
do local s="⬇" printh("RESULT g131 u2b07 len="..#s.." b="..ord(s)) end
do local s="░" printh("RESULT g132 u2591 len="..#s.." b="..ord(s)) end
do local s="✽" printh("RESULT g133 u273d len="..#s.." b="..ord(s)) end
do local s="●" printh("RESULT g134 u25cf len="..#s.." b="..ord(s)) end
do local s="♥" printh("RESULT g135 u2665 len="..#s.." b="..ord(s)) end
do local s="☉" printh("RESULT g136 u2609 len="..#s.." b="..ord(s)) end
do local s="웃" printh("RESULT g137 uc6c3 len="..#s.." b="..ord(s)) end
do local s="⌂" printh("RESULT g138 u2302 len="..#s.." b="..ord(s)) end
do local s="⬅" printh("RESULT g139 u2b05 len="..#s.." b="..ord(s)) end
do local s="😐" printh("RESULT g140 u1f610 len="..#s.." b="..ord(s)) end
do local s="♪" printh("RESULT g141 u266a len="..#s.." b="..ord(s)) end
do local s="🅾" printh("RESULT g142 u1f17e len="..#s.." b="..ord(s)) end
do local s="◆" printh("RESULT g143 u25c6 len="..#s.." b="..ord(s)) end
do local s="…" printh("RESULT g144 u2026 len="..#s.." b="..ord(s)) end
do local s="➡" printh("RESULT g145 u27a1 len="..#s.." b="..ord(s)) end
do local s="★" printh("RESULT g146 u2605 len="..#s.." b="..ord(s)) end
do local s="⧗" printh("RESULT g147 u29d7 len="..#s.." b="..ord(s)) end
do local s="⬆" printh("RESULT g148 u2b06 len="..#s.." b="..ord(s)) end
do local s="ˇ" printh("RESULT g149 u2c7 len="..#s.." b="..ord(s)) end
do local s="∧" printh("RESULT g150 u2227 len="..#s.." b="..ord(s)) end
do local s="❎" printh("RESULT g151 u274e len="..#s.." b="..ord(s)) end
do local s="▤" printh("RESULT g152 u25a4 len="..#s.." b="..ord(s)) end
do local s="▥" printh("RESULT g153 u25a5 len="..#s.." b="..ord(s)) end
do local s="あ" printh("RESULT g154 u3042 len="..#s.." b="..ord(s)) end
do local s="い" printh("RESULT g155 u3044 len="..#s.." b="..ord(s)) end
do local s="う" printh("RESULT g156 u3046 len="..#s.." b="..ord(s)) end
do local s="え" printh("RESULT g157 u3048 len="..#s.." b="..ord(s)) end
do local s="お" printh("RESULT g158 u304a len="..#s.." b="..ord(s)) end
do local s="か" printh("RESULT g159 u304b len="..#s.." b="..ord(s)) end
do local s="き" printh("RESULT g160 u304d len="..#s.." b="..ord(s)) end
do local s="く" printh("RESULT g161 u304f len="..#s.." b="..ord(s)) end
do local s="け" printh("RESULT g162 u3051 len="..#s.." b="..ord(s)) end
do local s="こ" printh("RESULT g163 u3053 len="..#s.." b="..ord(s)) end
do local s="さ" printh("RESULT g164 u3055 len="..#s.." b="..ord(s)) end
do local s="し" printh("RESULT g165 u3057 len="..#s.." b="..ord(s)) end
do local s="す" printh("RESULT g166 u3059 len="..#s.." b="..ord(s)) end
do local s="せ" printh("RESULT g167 u305b len="..#s.." b="..ord(s)) end
do local s="そ" printh("RESULT g168 u305d len="..#s.." b="..ord(s)) end
do local s="た" printh("RESULT g169 u305f len="..#s.." b="..ord(s)) end
do local s="ち" printh("RESULT g170 u3061 len="..#s.." b="..ord(s)) end
do local s="つ" printh("RESULT g171 u3064 len="..#s.." b="..ord(s)) end
do local s="て" printh("RESULT g172 u3066 len="..#s.." b="..ord(s)) end
do local s="と" printh("RESULT g173 u3068 len="..#s.." b="..ord(s)) end
do local s="な" printh("RESULT g174 u306a len="..#s.." b="..ord(s)) end
do local s="に" printh("RESULT g175 u306b len="..#s.." b="..ord(s)) end
do local s="ぬ" printh("RESULT g176 u306c len="..#s.." b="..ord(s)) end
do local s="ね" printh("RESULT g177 u306d len="..#s.." b="..ord(s)) end
do local s="の" printh("RESULT g178 u306e len="..#s.." b="..ord(s)) end
do local s="は" printh("RESULT g179 u306f len="..#s.." b="..ord(s)) end
do local s="ひ" printh("RESULT g180 u3072 len="..#s.." b="..ord(s)) end
do local s="ふ" printh("RESULT g181 u3075 len="..#s.." b="..ord(s)) end
do local s="へ" printh("RESULT g182 u3078 len="..#s.." b="..ord(s)) end
do local s="ほ" printh("RESULT g183 u307b len="..#s.." b="..ord(s)) end
do local s="ま" printh("RESULT g184 u307e len="..#s.." b="..ord(s)) end
do local s="み" printh("RESULT g185 u307f len="..#s.." b="..ord(s)) end
do local s="む" printh("RESULT g186 u3080 len="..#s.." b="..ord(s)) end
do local s="め" printh("RESULT g187 u3081 len="..#s.." b="..ord(s)) end
do local s="も" printh("RESULT g188 u3082 len="..#s.." b="..ord(s)) end
do local s="や" printh("RESULT g189 u3084 len="..#s.." b="..ord(s)) end
do local s="ゆ" printh("RESULT g190 u3086 len="..#s.." b="..ord(s)) end
do local s="よ" printh("RESULT g191 u3088 len="..#s.." b="..ord(s)) end
do local s="ら" printh("RESULT g192 u3089 len="..#s.." b="..ord(s)) end
do local s="り" printh("RESULT g193 u308a len="..#s.." b="..ord(s)) end
do local s="る" printh("RESULT g194 u308b len="..#s.." b="..ord(s)) end
do local s="れ" printh("RESULT g195 u308c len="..#s.." b="..ord(s)) end
do local s="ろ" printh("RESULT g196 u308d len="..#s.." b="..ord(s)) end
do local s="わ" printh("RESULT g197 u308f len="..#s.." b="..ord(s)) end
do local s="を" printh("RESULT g198 u3092 len="..#s.." b="..ord(s)) end
do local s="ん" printh("RESULT g199 u3093 len="..#s.." b="..ord(s)) end
do local s="っ" printh("RESULT g200 u3063 len="..#s.." b="..ord(s)) end
do local s="ゃ" printh("RESULT g201 u3083 len="..#s.." b="..ord(s)) end
do local s="ゅ" printh("RESULT g202 u3085 len="..#s.." b="..ord(s)) end
do local s="ょ" printh("RESULT g203 u3087 len="..#s.." b="..ord(s)) end
do local s="ア" printh("RESULT g204 u30a2 len="..#s.." b="..ord(s)) end
do local s="イ" printh("RESULT g205 u30a4 len="..#s.." b="..ord(s)) end
do local s="ウ" printh("RESULT g206 u30a6 len="..#s.." b="..ord(s)) end
do local s="エ" printh("RESULT g207 u30a8 len="..#s.." b="..ord(s)) end
do local s="オ" printh("RESULT g208 u30aa len="..#s.." b="..ord(s)) end
do local s="カ" printh("RESULT g209 u30ab len="..#s.." b="..ord(s)) end
do local s="キ" printh("RESULT g210 u30ad len="..#s.." b="..ord(s)) end
do local s="ク" printh("RESULT g211 u30af len="..#s.." b="..ord(s)) end
do local s="ケ" printh("RESULT g212 u30b1 len="..#s.." b="..ord(s)) end
do local s="コ" printh("RESULT g213 u30b3 len="..#s.." b="..ord(s)) end
do local s="サ" printh("RESULT g214 u30b5 len="..#s.." b="..ord(s)) end
do local s="シ" printh("RESULT g215 u30b7 len="..#s.." b="..ord(s)) end
do local s="ス" printh("RESULT g216 u30b9 len="..#s.." b="..ord(s)) end
do local s="セ" printh("RESULT g217 u30bb len="..#s.." b="..ord(s)) end
do local s="ソ" printh("RESULT g218 u30bd len="..#s.." b="..ord(s)) end
do local s="タ" printh("RESULT g219 u30bf len="..#s.." b="..ord(s)) end
do local s="チ" printh("RESULT g220 u30c1 len="..#s.." b="..ord(s)) end
do local s="ツ" printh("RESULT g221 u30c4 len="..#s.." b="..ord(s)) end
do local s="テ" printh("RESULT g222 u30c6 len="..#s.." b="..ord(s)) end
do local s="ト" printh("RESULT g223 u30c8 len="..#s.." b="..ord(s)) end
do local s="ナ" printh("RESULT g224 u30ca len="..#s.." b="..ord(s)) end
do local s="ニ" printh("RESULT g225 u30cb len="..#s.." b="..ord(s)) end
do local s="ヌ" printh("RESULT g226 u30cc len="..#s.." b="..ord(s)) end
do local s="ネ" printh("RESULT g227 u30cd len="..#s.." b="..ord(s)) end
do local s="ノ" printh("RESULT g228 u30ce len="..#s.." b="..ord(s)) end
do local s="ハ" printh("RESULT g229 u30cf len="..#s.." b="..ord(s)) end
do local s="ヒ" printh("RESULT g230 u30d2 len="..#s.." b="..ord(s)) end
do local s="フ" printh("RESULT g231 u30d5 len="..#s.." b="..ord(s)) end
do local s="ヘ" printh("RESULT g232 u30d8 len="..#s.." b="..ord(s)) end
do local s="ホ" printh("RESULT g233 u30db len="..#s.." b="..ord(s)) end
do local s="マ" printh("RESULT g234 u30de len="..#s.." b="..ord(s)) end
do local s="ミ" printh("RESULT g235 u30df len="..#s.." b="..ord(s)) end
do local s="ム" printh("RESULT g236 u30e0 len="..#s.." b="..ord(s)) end
do local s="メ" printh("RESULT g237 u30e1 len="..#s.." b="..ord(s)) end
do local s="モ" printh("RESULT g238 u30e2 len="..#s.." b="..ord(s)) end
do local s="ヤ" printh("RESULT g239 u30e4 len="..#s.." b="..ord(s)) end
do local s="ユ" printh("RESULT g240 u30e6 len="..#s.." b="..ord(s)) end
do local s="ヨ" printh("RESULT g241 u30e8 len="..#s.." b="..ord(s)) end
do local s="ラ" printh("RESULT g242 u30e9 len="..#s.." b="..ord(s)) end
do local s="リ" printh("RESULT g243 u30ea len="..#s.." b="..ord(s)) end
do local s="ル" printh("RESULT g244 u30eb len="..#s.." b="..ord(s)) end
do local s="レ" printh("RESULT g245 u30ec len="..#s.." b="..ord(s)) end
do local s="ロ" printh("RESULT g246 u30ed len="..#s.." b="..ord(s)) end
do local s="ワ" printh("RESULT g247 u30ef len="..#s.." b="..ord(s)) end
do local s="ヲ" printh("RESULT g248 u30f2 len="..#s.." b="..ord(s)) end
do local s="ン" printh("RESULT g249 u30f3 len="..#s.." b="..ord(s)) end
do local s="ッ" printh("RESULT g250 u30c3 len="..#s.." b="..ord(s)) end
do local s="ャ" printh("RESULT g251 u30e3 len="..#s.." b="..ord(s)) end
do local s="ュ" printh("RESULT g252 u30e5 len="..#s.." b="..ord(s)) end
do local s="ョ" printh("RESULT g253 u30e7 len="..#s.." b="..ord(s)) end
do local s="◜" printh("RESULT g254 u25dc len="..#s.." b="..ord(s)) end
do local s="◝" printh("RESULT g255 u25dd len="..#s.." b="..ord(s)) end
do local s="⬇️" printh("RESULT v131 u2b07fe0f len="..#s.." b="..ord(s)) end
do local s="⬅️" printh("RESULT v139 u2b05fe0f len="..#s.." b="..ord(s)) end
do local s="🅾️" printh("RESULT v142 u1f17efe0f len="..#s.." b="..ord(s)) end
do local s="➡️" printh("RESULT v145 u27a1fe0f len="..#s.." b="..ord(s)) end
do local s="⬆️" printh("RESULT v148 u2b06fe0f len="..#s.." b="..ord(s)) end
do local s="❎️" printh("RESULT v151 u274efe0f len="..#s.." b="..ord(s)) end
printh("DONE")
